apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: Darwin3-device-plugin
  namespace: kube-system
  labels:
    app: Darwin3-device-plugin
spec:
  selector:
    matchLabels:
      app: Darwin3-device-plugin
  template:
    metadata:
      labels:
        app: Darwin3-device-plugin
    spec:
      containers:
        - name: Darwin3-device-plugin
          image: docker.io/ldemon2333/darwin3-device-plugin:1.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
            - name: darwin3
              mountPath: /etc/darwin3
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: darwin3
          hostPath:
            path: /etc/darwin3
